# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-27 16:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import emtct.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('user_role', models.CharField(choices=[('data_clerk', 'Data Clerk'), ('admin', 'Administrator')], max_length=18)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', emtct.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50, null=True)),
                ('group', models.CharField(max_length=50)),
                ('last_visit_date', models.DateField(null=True)),
                ('next_appointment', models.DateField(null=True)),
                ('encounter_type', models.CharField(max_length=50, null=True)),
                ('art_number', models.CharField(max_length=50, null=True)),
                ('openmrs_id', models.CharField(max_length=50, null=True)),
                ('eid_number', models.CharField(max_length=50, null=True)),
                ('sex', models.CharField(max_length=50, null=True)),
                ('birth_date', models.CharField(max_length=50, null=True)),
                ('age_years', models.CharField(max_length=50, null=True)),
                ('health_facility', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parish', models.CharField(max_length=30, null=True)),
                ('sub_county', models.CharField(max_length=30, null=True)),
                ('county', models.CharField(max_length=30, null=True)),
                ('district', models.CharField(max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Health Facility',
                'verbose_name_plural': 'Health Facilities',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField()),
                ('phone', models.CharField(max_length=50)),
                ('follow_up_date', models.DateTimeField()),
                ('outcome', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emtct.Contact')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='RapidPro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('host', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'RapidPro',
                'verbose_name_plural': 'RapidPro',
            },
        ),
        migrations.CreateModel(
            name='UgandaEMRExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_file', models.FileField(upload_to='emtct_exports')),
                ('sync_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uganda EMR Export',
                'verbose_name_plural': 'Uganda EMR Exports',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='uganda_emr_export',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emtct.UgandaEMRExport'),
        ),
        migrations.AddField(
            model_name='user',
            name='health_facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emtct.HealthFacility'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
