# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emtct', '0004_auto_20181104_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='label',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
