# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emtct', '0005_message_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthfacility',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='county',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='parish',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='sub_county',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
