# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-01 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emtct', '0007_auto_20181107_0643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-created_at',), 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='healthfacility',
            options={'ordering': ('name',), 'verbose_name': 'Health Facility', 'verbose_name_plural': 'Health Facilities'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created_at',), 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='rapidpro',
            options={'ordering': ('-created_at',), 'verbose_name': 'RapidPro', 'verbose_name_plural': 'RapidPro'},
        ),
        migrations.AlterModelOptions(
            name='ugandaemrexport',
            options={'ordering': ('-created_at',), 'verbose_name': 'Uganda EMR Export', 'verbose_name_plural': 'Uganda EMR Exports'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-created_at', 'user_role'), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='county',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='district',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='parish',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='healthfacility',
            name='sub_county',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('data_clerk', 'Data Clerk'), ('admin', 'Administrator'), ('health_information_assistant', 'Health Information Assistant '), ('data_assistant', 'Data Assistant'), ('enrolled_midwife', 'Enrolled Midwife'), ('records_officer ', 'Records Officer'), ('enrolled_midwife', 'Enrolled Midwife'), ('registered_midwives', 'Registered Midwives'), ('HMIS_officers ', 'HMIS Officers ')], max_length=18),
        ),
    ]
