# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-11-23 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emtct', '0008_auto_20190102_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('data_clerk', 'Data Clerk'), ('admin', 'Administrator'), ('sno', 'SNO'), ('no', 'NO'), ('smo', 'SMO'), ('hia', 'HIA'), ('sro', 'SRO'), ('dhe', 'DHE'), ('dhi', 'DHI'), ('biostat', 'Biostat'), ('pmtct_fp', 'PMTCT FP'), ('adho', 'ADHO'), ('mo', 'MO'), ('hmis_officer', 'HMIS Officer'), ('data_assistant', 'Data Assistant'), ('enrolled_midwife', 'Enrolled Midwife'), ('records_officer ', 'Records Officer'), ('enrolled_midwife', 'Enrolled Midwife'), ('registered_midwives', 'Registered Midwives'), ('HMIS_officers ', 'HMIS Officers '), ('Counselor', 'Counselor'), ('Clinical Officer', 'Clinical Officer'), ('Generic User', 'Generic User')], max_length=36),
        ),
    ]
