# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2022-04-06 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emtct', '0009_auto_20201123_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapidpro',
            name='smsChannel',
            field=models.CharField(default='test', max_length=36),
            preserve_default=False,
        ),
    ]
