# Generated by Django 4.0 on 2022-09-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emtct', '0012_auto_20220406_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='FcappOrgunits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=230)),
                ('code', models.CharField(max_length=50)),
                ('shortname', models.CharField(blank=True, max_length=50, null=True)),
                ('parentid', models.BigIntegerField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('hierarchylevel', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'fcapp_orgunits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubmittedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=45)),
                ('contact_unit', models.JSONField()),
            ],
        ),
    ]
