# Generated by Django 4.0 on 2022-09-29 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emtct', '0014_submitteddata_created_at_submitteddata_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcapporgunits',
            options={'managed': True},
        ),
    ]
